[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Go2 Deploy Baseline Lab"
author = "iamjaehka13"
maintainer = "iamjaehka13"
description="Isaac Lab Go2 deploy baseline with real-policy observation layout"
repository = "https://github.com/iamjaehka13/unitree_go2_deploy_baseline_fullcode_lab"
keywords = ["isaaclab", "unitree", "go2", "locomotion", "sim-to-real"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "go2_deploy_lab"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
